# wrangler.toml

# This is the name of your Cloudflare Pages project.
# It will be created if it doesn't exist upon your first deployment.
name = "duelim-site"

# Using a recent compatibility date is best practice to ensure access
# to the latest Cloudflare features and improvements.
compatibility_date = "2025-06-25"

# The [pages] section specifies configuration for a Cloudflare Pages project.
[pages]
# This is the directory that contains your static assets (HTML files, CSS, images, etc.).
# Wrangler will upload the contents of this directory to Cloudflare Pages.
# You should create a folder named "public" and place your HTML files inside it.
# - duelim_landing_page.html -> public/index.html
# - duelim_services_page.html -> public/services.html
upload_dir = "public"
